<?xml version="1.0" ?>
<robot name="motoman_mh_180_120" xmlns:xacro="http://ros.org/wiki/xacro" xmlns:tesseract="https://github.com/tesseract-robotics/tesseract" tesseract:make_convex="true">

  <xacro:macro name="cuboid" params="name l w h material offset=False">
    <link name="${name}">
      <visual>
        <xacro:if value="${offset}" >
          <origin xyz="${l / 2.0} ${w / 2.0} ${-h / 2.0}" />
        </xacro:if>
        <geometry>
          <box size="${l} ${w} ${h}"/>
        </geometry>
        <material name="${material}"/>
      </visual>
      <collision>
        <xacro:if value="${offset}" >
          <origin xyz="${l / 2.0} ${w / 2.0} ${-h / 2.0}" />
        </xacro:if>
        <geometry>
          <box size="${l} ${w} ${h}"/>
        </geometry>
        <material name="${material}"/>
      </collision>
    </link>
  </xacro:macro>

  <xacro:include filename="$(find snp_blending)/urdf/ros2_control.xacro"/>
  <xacro:snp_blending_ros2_control name="SNP Blending ROS2 Control" prefix=""/>

  <xacro:include filename="$(find snp_blending)/urdf/mh180_120/mh180_120_macro.xacro"/>
  <xacro:motoman_mh180_120 prefix=""/>

  <xacro:include filename="$(find snp_blending)/urdf/pushcorp.xacro"/>
  <xacro:pushcorp prefix="pushcorp_"/>

  <material name="light_gray">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>

  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>

  <link name="floor"/>

  <xacro:property name="platform_length" value="${96 * 0.0254}"/>
  <xacro:property name="platform_width" value="${72 * 0.0254}"/>
  <xacro:property name="platform_height" value="${5 * 0.0254}"/>
  <xacro:cuboid name="platform" l="${platform_length}" w="${platform_width}" h="${platform_height}" material="dark_gray"/>

  <xacro:property name="robot_mount_width" value="${28.5 * 0.0254}"/>
  <xacro:property name="robot_mount_height" value="${19.6 * 0.0254}"/>
  <xacro:cuboid name="robot_mount" l="${robot_mount_width}" w="${robot_mount_width}" h="${robot_mount_height}" material="dark_gray"/>

  <xacro:property name="pushcorp_box_support_width" value="${1.5 * 0.0254}"/>
  <xacro:property name="pushcorp_box_support_height" value="${40.5 * 0.0254}"/>
  <xacro:cuboid name="pushcorp_box_support_1" l="${pushcorp_box_support_width}" w="${pushcorp_box_support_width}" h="${pushcorp_box_support_height}" material="light_gray"/>
  <xacro:cuboid name="pushcorp_box_support_2" l="${pushcorp_box_support_width}" w="${pushcorp_box_support_width}" h="${pushcorp_box_support_height}" material="light_gray"/>

  <xacro:property name="pushcorp_box_length" value="${28 * 0.0254}"/>
  <xacro:property name="pushcorp_box_width" value="${17 * 0.0254}"/>
  <xacro:property name="pushcorp_box_height" value="${30 * 0.0254}"/>
  <xacro:cuboid name="pushcorp_box" l="${pushcorp_box_length}" w="${pushcorp_box_width}" h="${pushcorp_box_height}" material="light_gray"/>

  <link name="buffy_tcp"/>
  <joint name="buffy_tcp_joint" type="fixed">
    <parent link="tool0"/>
    <child link="buffy_tcp"/>
    <origin xyz="0.265 0 0.19" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="floor_to_platform" type="fixed">
    <parent link="floor"/>
    <child link="platform"/>
    <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
  </joint>

  <joint name="platform_to_mount" type="fixed">
    <parent link="platform"/>
    <child link="robot_mount"/>
    <origin xyz="0 0 ${platform_height/2 + robot_mount_height/2}" rpy="0 0 0"/>
  </joint>

  <joint name="floor_to_pushcorp_support_1" type="fixed">
    <parent link="floor"/>
    <child link="pushcorp_box_support_1"/>
    <origin xyz="-${robot_mount_width/2 + 2.75*0.0254} ${robot_mount_width/2 + 16.25*0.0254} ${20.25*0.0254+platform_height}" rpy="0 0 0"/>
  </joint>

  <joint name="floor_to_pushcorp_support_2" type="fixed">
    <parent link="floor"/>
    <child link="pushcorp_box_support_2"/>
    <origin xyz="-${robot_mount_width/2 + 1.25*0.0254 + pushcorp_box_length} ${robot_mount_width/2 + 16.25*0.0254} ${20.25*0.0254+platform_height}" rpy="0 0 0"/>
  </joint>

  <joint name="floor_to_pushcorp_box" type="fixed">
    <parent link="floor"/>
    <child link="pushcorp_box"/>
    <origin xyz="-${robot_mount_width/2 + 2*0.0254 + pushcorp_box_length/2} ${robot_mount_width/2 + 17*0.0254 + pushcorp_box_width/2} ${14*0.0254 + pushcorp_box_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Robot to mount -->
  <joint name="mount_to_base" type="fixed">
    <parent link="robot_mount"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${robot_mount_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Pushcorp to robot -->
  <joint name="tool0_to_pushcorp_base" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_base"/>
  </joint>

  <!-- Camera Calibration-->
  <xacro:arg name="ros_distro" default="humble"/>
  <xacro:if value="${'$(arg ros_distro)' > 'foxy'}">
    <xacro:property name="camera_cal" value="${xacro.load_yaml('$(find snp_blending)/config/calibration.yaml')}" />
  </xacro:if>
  <xacro:unless value="${'$(arg ros_distro)' > 'foxy'}">
    <xacro:property name="camera_cal" value="${load_yaml('$(find snp_blending)/config/calibration.yaml')}" />
  </xacro:unless>

  <link name="camera_color_optical_frame"/>
  <joint name="tool0_to_camera" type="fixed">
    <parent link="tool0"/>
    <child link="camera_color_optical_frame"/>
    <origin xyz="${camera_cal['camera_mount_to_camera_pos']['x']} ${camera_cal['camera_mount_to_camera_pos']['y']} ${camera_cal['camera_mount_to_camera_pos']['z']}"
            rpy="${camera_cal['camera_mount_to_camera_rpy']['x']} ${camera_cal['camera_mount_to_camera_rpy']['y']} ${camera_cal['camera_mount_to_camera_rpy']['z']}" />
  </joint>

  <link name="cal_target_frame"/>
  <joint name="target_mount_to_target" type="fixed">
    <parent link="base_link"/>
    <child link="cal_target_frame"/>
    <origin xyz="${camera_cal['target_mount_to_target_pos']['x']} ${camera_cal['target_mount_to_target_pos']['y']} ${camera_cal['target_mount_to_target_pos']['z']}"
            rpy="${camera_cal['target_mount_to_target_rpy']['x']} ${camera_cal['target_mount_to_target_rpy']['y']} ${camera_cal['target_mount_to_target_rpy']['z']}" />
  </joint>

  <!-- Table -->
  <xacro:property name="table_height" value="${37*0.0254}"/>
  <xacro:property name="table_width" value="${60*0.0254}"/>
  <xacro:property name="table_length" value="${36*0.0254}"/>
  <xacro:if value="${'$(arg ros_distro)' > 'foxy'}">
    <xacro:property name="table_cal" value="${xacro.load_yaml('$(find snp_blending)/config/table_calibration.yaml')}" />
  </xacro:if>
  <xacro:unless value="${'$(arg ros_distro)' > 'foxy'}">
    <xacro:property name="table_cal" value="${load_yaml('$(find snp_blending)/config/table_calibration.yaml')}" />
  </xacro:unless>

  <xacro:cuboid name="table" l="${table_length}" w="${table_width}" h="${table_height}" material="light_gray" offset="True"/>

  <joint name="floor_to_table" type="fixed">
    <parent link="floor"/>
    <child link="table"/>
    <origin xyz="${table_cal['x']} ${table_cal['y']} ${table_cal['z']}" rpy="${table_cal['roll']} ${table_cal['pitch']} ${table_cal['yaw']}" />
  </joint>
</robot>
