mesh_modifiers:
  - name: ROISelectionMeshModifier
    max_cluster_size: 1000000000
    min_cluster_size: 100
    cluster_tolerance: 0.1
    plane_distance_threshold: 0.1
  - distance_threshold: 0.005
    max_planes: 0
    min_vertices: 1
    name: PlaneProjectionModifier
tool_path_planner:
  name: PlaneSlicerRasterPlanner
  direction_generator:
    name: FixedDirectionGenerator
    x: 0
    y: 1
    z: 0
  origin_generator:
    name: FixedOriginGenerator
    x: 0
    y: 0
    z: 0
  line_spacing: 0.015
  point_spacing: 0.015
  min_hole_size: 0.1
  search_radius: 0.03
  min_segment_size: 0.1
tool_path_modifiers:
  - name: MovingAverageOrientationSmoothingModifier
    window_size: 5
  - name: SnakeOrganizationModifier
  - name: CircularLeadInModifier
    arc_angle: 1.0472
    arc_radius: 0.05
    n_points: 3
  - name: CircularLeadOutModifier
    arc_angle: 1.0472
    arc_radius: 0.05
    n_points: 3
  - name: ToolDragOrientationToolPathModifier
    angle_offset: 0.1745
    tool_radius: 0.05
