name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  ci:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [humble]
    container:
      image: ghcr.io/ros-industrial-consortium/scan_n_plan_workshop:${{ matrix.distro }}-5.0
      env:
        CCACHE_DIR: ${{ github.workspace }}/${{ matrix.distro }}/.ccache
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: target_ws/src

      - name: Build and Tests
        uses: tesseract-robotics/colcon-action@v6
        with:
          before-script: source /opt/snp/install/setup.bash
          ccache-prefix: ${{ matrix.distro }}
          target-path: target_ws/src
          target-args: --cmake-args -DCMAKE_BUILD_TYPE=Debug
